package com.pku.xinfeng.dao;

import com.pku.xinfeng.model.CityCode;
import com.pku.xinfeng.model.CityCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CityCodeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city_code
	 * @mbggenerated
	 */
	int countByExample(CityCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city_code
	 * @mbggenerated
	 */
	int deleteByExample(CityCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city_code
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city_code
	 * @mbggenerated
	 */
	int insert(CityCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city_code
	 * @mbggenerated
	 */
	int insertSelective(CityCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city_code
	 * @mbggenerated
	 */
	List<CityCode> selectByExample(CityCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city_code
	 * @mbggenerated
	 */
	CityCode selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city_code
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") CityCode record,
			@Param("example") CityCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city_code
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") CityCode record,
			@Param("example") CityCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city_code
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CityCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city_code
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CityCode record);
}