package com.pku.xinfeng.dao;

import com.pku.xinfeng.model.Equipment;
import com.pku.xinfeng.model.EquipmentExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface EquipmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipment
	 * @mbggenerated
	 */
	int countByExample(EquipmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipment
	 * @mbggenerated
	 */
	int deleteByExample(EquipmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipment
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipment
	 * @mbggenerated
	 */
	int insert(Equipment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipment
	 * @mbggenerated
	 */
	int insertSelective(Equipment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipment
	 * @mbggenerated
	 */
	List<Equipment> selectByExample(EquipmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipment
	 * @mbggenerated
	 */
	Equipment selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipment
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Equipment record,
			@Param("example") EquipmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipment
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Equipment record,
			@Param("example") EquipmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipment
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Equipment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipment
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Equipment record);

	int addEquipment(Equipment record);
	
	Integer getMaxAirflow(String equipId);
}