package com.pku.xinfeng.dao;

import com.pku.xinfeng.model.SensorData;
import com.pku.xinfeng.model.SensorDataExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SensorDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	int countByExample(SensorDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	int deleteByExample(SensorDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	int insert(SensorData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	int insertSelective(SensorData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	List<SensorData> selectByExample(SensorDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	SensorData selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") SensorData record,
			@Param("example") SensorDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") SensorData record,
			@Param("example") SensorDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SensorData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SensorData record);

	List<SensorData> getEquipSensorListByUserId(String userId);
	
	List<SensorData> getHistory(String equipId);
}