package com.pku.xinfeng.dao;

import com.pku.xinfeng.model.Temperature;
import com.pku.xinfeng.model.TemperatureExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TemperatureMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	int countByExample(TemperatureExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	int deleteByExample(TemperatureExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	int insert(Temperature record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	int insertSelective(Temperature record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	List<Temperature> selectByExample(TemperatureExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	Temperature selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Temperature record,
			@Param("example") TemperatureExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Temperature record,
			@Param("example") TemperatureExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Temperature record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Temperature record);
	int deleteAll();
    int insertBatch(List<Temperature> list);
}