package com.pku.xinfeng.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.pku.xinfeng.model.TimeSet;
import com.pku.xinfeng.model.TimeSetExample;

public interface TimeSetMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_set
	 * @mbggenerated
	 */
	int countByExample(TimeSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_set
	 * @mbggenerated
	 */
	int deleteByExample(TimeSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_set
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_set
	 * @mbggenerated
	 */
	int insert(TimeSet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_set
	 * @mbggenerated
	 */
	int insertSelective(TimeSet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_set
	 * @mbggenerated
	 */
	List<TimeSet> selectByExample(TimeSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_set
	 * @mbggenerated
	 */
	TimeSet selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_set
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") TimeSet record,
			@Param("example") TimeSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_set
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") TimeSet record,
			@Param("example") TimeSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_set
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(TimeSet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_set
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TimeSet record);

	int updateStatusByEquipId(Map<String,Object> map);
}