package com.pku.xinfeng.dao;

import com.pku.xinfeng.model.UserEquipment;
import com.pku.xinfeng.model.UserEquipmentExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface UserEquipmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	int countByExample(UserEquipmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	int deleteByExample(UserEquipmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	int insert(UserEquipment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	int insertSelective(UserEquipment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	List<UserEquipment> selectByExample(UserEquipmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	UserEquipment selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") UserEquipment record,
			@Param("example") UserEquipmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") UserEquipment record,
			@Param("example") UserEquipmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UserEquipment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UserEquipment record);

	int updateEquipName(Map<String, Object> map);
}