package com.pku.xinfeng.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pku.xinfeng.model.UserWeather;
import com.pku.xinfeng.model.UserWeatherExample;

public interface UserWeatherMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_weather
	 * @mbggenerated
	 */
	int countByExample(UserWeatherExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_weather
	 * @mbggenerated
	 */
	int deleteByExample(UserWeatherExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_weather
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_weather
	 * @mbggenerated
	 */
	int insert(UserWeather record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_weather
	 * @mbggenerated
	 */
	int insertSelective(UserWeather record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_weather
	 * @mbggenerated
	 */
	List<UserWeather> selectByExample(UserWeatherExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_weather
	 * @mbggenerated
	 */
	UserWeather selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_weather
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") UserWeather record,
			@Param("example") UserWeatherExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_weather
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") UserWeather record,
			@Param("example") UserWeatherExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_weather
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UserWeather record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_weather
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UserWeather record);
}