package com.pku.xinfeng.dao;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pku.xinfeng.model.Version;
import com.pku.xinfeng.model.VersionExample;

public interface VersionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated
	 */
	int countByExample(VersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated
	 */
	int deleteByExample(VersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated
	 */
	int insert(Version record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated
	 */
	int insertSelective(Version record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated
	 */
	List<Version> selectByExample(VersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated
	 */
	Version selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Version record,
			@Param("example") VersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Version record,
			@Param("example") VersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Version record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Version record);
	
	List<HashMap<String,Object>> getListByVersion(Integer id);
}