package com.pku.xinfeng.dao;

import com.pku.xinfeng.model.Weather;
import com.pku.xinfeng.model.WeatherExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface WeatherMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	int countByExample(WeatherExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	int deleteByExample(WeatherExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	int insert(Weather record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	int insertSelective(Weather record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	List<Weather> selectByExample(WeatherExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Weather record,
			@Param("example") WeatherExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Weather record,
			@Param("example") WeatherExample example);
	List<Weather> getWeatherListByUserId(String userId);
	List<Weather> getCityList();
}