package com.pku.xinfeng.model;

public class CityCode {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column city_code.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column city_code.cityName
	 * @mbggenerated
	 */
	private String cityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column city_code.cityNameEn
	 * @mbggenerated
	 */
	private String cityNameEn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column city_code.note
	 * @mbggenerated
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column city_code.id
	 * @return  the value of city_code.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column city_code.id
	 * @param id  the value for city_code.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column city_code.cityName
	 * @return  the value of city_code.cityName
	 * @mbggenerated
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column city_code.cityName
	 * @param cityName  the value for city_code.cityName
	 * @mbggenerated
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName == null ? null : cityName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column city_code.cityNameEn
	 * @return  the value of city_code.cityNameEn
	 * @mbggenerated
	 */
	public String getCityNameEn() {
		return cityNameEn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column city_code.cityNameEn
	 * @param cityNameEn  the value for city_code.cityNameEn
	 * @mbggenerated
	 */
	public void setCityNameEn(String cityNameEn) {
		this.cityNameEn = cityNameEn == null ? null : cityNameEn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column city_code.note
	 * @return  the value of city_code.note
	 * @mbggenerated
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column city_code.note
	 * @param note  the value for city_code.note
	 * @mbggenerated
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}
}