package com.pku.xinfeng.model;

import java.util.Date;

public class Command {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column command.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column command.equip_id
	 * @mbggenerated
	 */
	private String equip_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column command.command
	 * @mbggenerated
	 */
	private String command;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column command.type
	 * @mbggenerated
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column command.status
	 * @mbggenerated
	 */
	private Boolean status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column command.update_date
	 * @mbggenerated
	 */
	private Date update_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column command.note
	 * @mbggenerated
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column command.id
	 * @return  the value of command.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column command.id
	 * @param id  the value for command.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column command.equip_id
	 * @return  the value of command.equip_id
	 * @mbggenerated
	 */
	public String getEquip_id() {
		return equip_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column command.equip_id
	 * @param equip_id  the value for command.equip_id
	 * @mbggenerated
	 */
	public void setEquip_id(String equip_id) {
		this.equip_id = equip_id == null ? null : equip_id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column command.command
	 * @return  the value of command.command
	 * @mbggenerated
	 */
	public String getCommand() {
		return command;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column command.command
	 * @param command  the value for command.command
	 * @mbggenerated
	 */
	public void setCommand(String command) {
		this.command = command == null ? null : command.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column command.type
	 * @return  the value of command.type
	 * @mbggenerated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column command.type
	 * @param type  the value for command.type
	 * @mbggenerated
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column command.status
	 * @return  the value of command.status
	 * @mbggenerated
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column command.status
	 * @param status  the value for command.status
	 * @mbggenerated
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column command.update_date
	 * @return  the value of command.update_date
	 * @mbggenerated
	 */
	public Date getUpdate_date() {
		return update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column command.update_date
	 * @param update_date  the value for command.update_date
	 * @mbggenerated
	 */
	public void setUpdate_date(Date update_date) {
		this.update_date = update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column command.note
	 * @return  the value of command.note
	 * @mbggenerated
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column command.note
	 * @param note  the value for command.note
	 * @mbggenerated
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}
}