package com.pku.xinfeng.model;

import java.util.Date;

public class OperLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column oper_log.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column oper_log.oper_type
	 * @mbggenerated
	 */
	private String oper_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column oper_log.oper_data
	 * @mbggenerated
	 */
	private String oper_data;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column oper_log.oper_time
	 * @mbggenerated
	 */
	private Date oper_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column oper_log.oper_user_id
	 * @mbggenerated
	 */
	private String oper_user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column oper_log.oper_equi_id
	 * @mbggenerated
	 */
	private String oper_equi_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column oper_log.oper_level
	 * @mbggenerated
	 */
	private String oper_level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column oper_log.note
	 * @mbggenerated
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column oper_log.id
	 * @return  the value of oper_log.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column oper_log.id
	 * @param id  the value for oper_log.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column oper_log.oper_type
	 * @return  the value of oper_log.oper_type
	 * @mbggenerated
	 */
	public String getOper_type() {
		return oper_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column oper_log.oper_type
	 * @param oper_type  the value for oper_log.oper_type
	 * @mbggenerated
	 */
	public void setOper_type(String oper_type) {
		this.oper_type = oper_type == null ? null : oper_type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column oper_log.oper_data
	 * @return  the value of oper_log.oper_data
	 * @mbggenerated
	 */
	public String getOper_data() {
		return oper_data;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column oper_log.oper_data
	 * @param oper_data  the value for oper_log.oper_data
	 * @mbggenerated
	 */
	public void setOper_data(String oper_data) {
		this.oper_data = oper_data == null ? null : oper_data.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column oper_log.oper_time
	 * @return  the value of oper_log.oper_time
	 * @mbggenerated
	 */
	public Date getOper_time() {
		return oper_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column oper_log.oper_time
	 * @param oper_time  the value for oper_log.oper_time
	 * @mbggenerated
	 */
	public void setOper_time(Date oper_time) {
		this.oper_time = oper_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column oper_log.oper_user_id
	 * @return  the value of oper_log.oper_user_id
	 * @mbggenerated
	 */
	public String getOper_user_id() {
		return oper_user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column oper_log.oper_user_id
	 * @param oper_user_id  the value for oper_log.oper_user_id
	 * @mbggenerated
	 */
	public void setOper_user_id(String oper_user_id) {
		this.oper_user_id = oper_user_id == null ? null : oper_user_id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column oper_log.oper_equi_id
	 * @return  the value of oper_log.oper_equi_id
	 * @mbggenerated
	 */
	public String getOper_equi_id() {
		return oper_equi_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column oper_log.oper_equi_id
	 * @param oper_equi_id  the value for oper_log.oper_equi_id
	 * @mbggenerated
	 */
	public void setOper_equi_id(String oper_equi_id) {
		this.oper_equi_id = oper_equi_id == null ? null : oper_equi_id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column oper_log.oper_level
	 * @return  the value of oper_log.oper_level
	 * @mbggenerated
	 */
	public String getOper_level() {
		return oper_level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column oper_log.oper_level
	 * @param oper_level  the value for oper_log.oper_level
	 * @mbggenerated
	 */
	public void setOper_level(String oper_level) {
		this.oper_level = oper_level == null ? null : oper_level.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column oper_log.note
	 * @return  the value of oper_log.note
	 * @mbggenerated
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column oper_log.note
	 * @param note  the value for oper_log.note
	 * @mbggenerated
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	private Date operDateBegin;
	private Date operDateEnd;

	public Date getOperDateBegin() {
		return operDateBegin;
	}

	public void setOperDateBegin(Date operDateBegin) {
		this.operDateBegin = operDateBegin;
	}

	public Date getOperDateEnd() {
		return operDateEnd;
	}

	public void setOperDateEnd(Date operDateEnd) {
		this.operDateEnd = operDateEnd;
	}
}