package com.pku.xinfeng.model;

import java.util.Date;

public class Pm {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm.cityId
	 * @mbggenerated
	 */
	private String cityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm.cityName
	 * @mbggenerated
	 */
	private String cityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm.aqi
	 * @mbggenerated
	 */
	private String aqi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm.co
	 * @mbggenerated
	 */
	private String co;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm.o3
	 * @mbggenerated
	 */
	private String o3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm.so2
	 * @mbggenerated
	 */
	private String so2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm.no2
	 * @mbggenerated
	 */
	private String no2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm.pm10
	 * @mbggenerated
	 */
	private String pm10;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm.pm25
	 * @mbggenerated
	 */
	private String pm25;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm.update_date
	 * @mbggenerated
	 */
	private Date update_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm.note
	 * @mbggenerated
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm.id
	 * @return  the value of pm.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm.id
	 * @param id  the value for pm.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm.cityId
	 * @return  the value of pm.cityId
	 * @mbggenerated
	 */
	public String getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm.cityId
	 * @param cityId  the value for pm.cityId
	 * @mbggenerated
	 */
	public void setCityId(String cityId) {
		this.cityId = cityId == null ? null : cityId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm.cityName
	 * @return  the value of pm.cityName
	 * @mbggenerated
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm.cityName
	 * @param cityName  the value for pm.cityName
	 * @mbggenerated
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName == null ? null : cityName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm.aqi
	 * @return  the value of pm.aqi
	 * @mbggenerated
	 */
	public String getAqi() {
		return aqi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm.aqi
	 * @param aqi  the value for pm.aqi
	 * @mbggenerated
	 */
	public void setAqi(String aqi) {
		this.aqi = aqi == null ? null : aqi.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm.co
	 * @return  the value of pm.co
	 * @mbggenerated
	 */
	public String getCo() {
		return co;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm.co
	 * @param co  the value for pm.co
	 * @mbggenerated
	 */
	public void setCo(String co) {
		this.co = co == null ? null : co.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm.o3
	 * @return  the value of pm.o3
	 * @mbggenerated
	 */
	public String getO3() {
		return o3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm.o3
	 * @param o3  the value for pm.o3
	 * @mbggenerated
	 */
	public void setO3(String o3) {
		this.o3 = o3 == null ? null : o3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm.so2
	 * @return  the value of pm.so2
	 * @mbggenerated
	 */
	public String getSo2() {
		return so2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm.so2
	 * @param so2  the value for pm.so2
	 * @mbggenerated
	 */
	public void setSo2(String so2) {
		this.so2 = so2 == null ? null : so2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm.no2
	 * @return  the value of pm.no2
	 * @mbggenerated
	 */
	public String getNo2() {
		return no2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm.no2
	 * @param no2  the value for pm.no2
	 * @mbggenerated
	 */
	public void setNo2(String no2) {
		this.no2 = no2 == null ? null : no2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm.pm10
	 * @return  the value of pm.pm10
	 * @mbggenerated
	 */
	public String getPm10() {
		return pm10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm.pm10
	 * @param pm10  the value for pm.pm10
	 * @mbggenerated
	 */
	public void setPm10(String pm10) {
		this.pm10 = pm10 == null ? null : pm10.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm.pm25
	 * @return  the value of pm.pm25
	 * @mbggenerated
	 */
	public String getPm25() {
		return pm25;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm.pm25
	 * @param pm25  the value for pm.pm25
	 * @mbggenerated
	 */
	public void setPm25(String pm25) {
		this.pm25 = pm25 == null ? null : pm25.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm.update_date
	 * @return  the value of pm.update_date
	 * @mbggenerated
	 */
	public Date getUpdate_date() {
		return update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm.update_date
	 * @param update_date  the value for pm.update_date
	 * @mbggenerated
	 */
	public void setUpdate_date(Date update_date) {
		this.update_date = update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm.note
	 * @return  the value of pm.note
	 * @mbggenerated
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm.note
	 * @param note  the value for pm.note
	 * @mbggenerated
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}
}