package com.pku.xinfeng.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PmExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pm
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pm
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pm
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pm
	 * @mbggenerated
	 */
	public PmExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pm
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pm
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pm
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pm
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pm
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pm
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pm
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pm
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pm
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pm
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pm
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCityIdIsNull() {
			addCriterion("cityId is null");
			return (Criteria) this;
		}

		public Criteria andCityIdIsNotNull() {
			addCriterion("cityId is not null");
			return (Criteria) this;
		}

		public Criteria andCityIdEqualTo(String value) {
			addCriterion("cityId =", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotEqualTo(String value) {
			addCriterion("cityId <>", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdGreaterThan(String value) {
			addCriterion("cityId >", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdGreaterThanOrEqualTo(String value) {
			addCriterion("cityId >=", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdLessThan(String value) {
			addCriterion("cityId <", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdLessThanOrEqualTo(String value) {
			addCriterion("cityId <=", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdLike(String value) {
			addCriterion("cityId like", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotLike(String value) {
			addCriterion("cityId not like", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdIn(List<String> values) {
			addCriterion("cityId in", values, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotIn(List<String> values) {
			addCriterion("cityId not in", values, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdBetween(String value1, String value2) {
			addCriterion("cityId between", value1, value2, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotBetween(String value1, String value2) {
			addCriterion("cityId not between", value1, value2, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityNameIsNull() {
			addCriterion("cityName is null");
			return (Criteria) this;
		}

		public Criteria andCityNameIsNotNull() {
			addCriterion("cityName is not null");
			return (Criteria) this;
		}

		public Criteria andCityNameEqualTo(String value) {
			addCriterion("cityName =", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameNotEqualTo(String value) {
			addCriterion("cityName <>", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameGreaterThan(String value) {
			addCriterion("cityName >", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameGreaterThanOrEqualTo(String value) {
			addCriterion("cityName >=", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameLessThan(String value) {
			addCriterion("cityName <", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameLessThanOrEqualTo(String value) {
			addCriterion("cityName <=", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameLike(String value) {
			addCriterion("cityName like", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameNotLike(String value) {
			addCriterion("cityName not like", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameIn(List<String> values) {
			addCriterion("cityName in", values, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameNotIn(List<String> values) {
			addCriterion("cityName not in", values, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameBetween(String value1, String value2) {
			addCriterion("cityName between", value1, value2, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameNotBetween(String value1, String value2) {
			addCriterion("cityName not between", value1, value2, "cityName");
			return (Criteria) this;
		}

		public Criteria andAqiIsNull() {
			addCriterion("aqi is null");
			return (Criteria) this;
		}

		public Criteria andAqiIsNotNull() {
			addCriterion("aqi is not null");
			return (Criteria) this;
		}

		public Criteria andAqiEqualTo(String value) {
			addCriterion("aqi =", value, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiNotEqualTo(String value) {
			addCriterion("aqi <>", value, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiGreaterThan(String value) {
			addCriterion("aqi >", value, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiGreaterThanOrEqualTo(String value) {
			addCriterion("aqi >=", value, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiLessThan(String value) {
			addCriterion("aqi <", value, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiLessThanOrEqualTo(String value) {
			addCriterion("aqi <=", value, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiLike(String value) {
			addCriterion("aqi like", value, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiNotLike(String value) {
			addCriterion("aqi not like", value, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiIn(List<String> values) {
			addCriterion("aqi in", values, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiNotIn(List<String> values) {
			addCriterion("aqi not in", values, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiBetween(String value1, String value2) {
			addCriterion("aqi between", value1, value2, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiNotBetween(String value1, String value2) {
			addCriterion("aqi not between", value1, value2, "aqi");
			return (Criteria) this;
		}

		public Criteria andCoIsNull() {
			addCriterion("co is null");
			return (Criteria) this;
		}

		public Criteria andCoIsNotNull() {
			addCriterion("co is not null");
			return (Criteria) this;
		}

		public Criteria andCoEqualTo(String value) {
			addCriterion("co =", value, "co");
			return (Criteria) this;
		}

		public Criteria andCoNotEqualTo(String value) {
			addCriterion("co <>", value, "co");
			return (Criteria) this;
		}

		public Criteria andCoGreaterThan(String value) {
			addCriterion("co >", value, "co");
			return (Criteria) this;
		}

		public Criteria andCoGreaterThanOrEqualTo(String value) {
			addCriterion("co >=", value, "co");
			return (Criteria) this;
		}

		public Criteria andCoLessThan(String value) {
			addCriterion("co <", value, "co");
			return (Criteria) this;
		}

		public Criteria andCoLessThanOrEqualTo(String value) {
			addCriterion("co <=", value, "co");
			return (Criteria) this;
		}

		public Criteria andCoLike(String value) {
			addCriterion("co like", value, "co");
			return (Criteria) this;
		}

		public Criteria andCoNotLike(String value) {
			addCriterion("co not like", value, "co");
			return (Criteria) this;
		}

		public Criteria andCoIn(List<String> values) {
			addCriterion("co in", values, "co");
			return (Criteria) this;
		}

		public Criteria andCoNotIn(List<String> values) {
			addCriterion("co not in", values, "co");
			return (Criteria) this;
		}

		public Criteria andCoBetween(String value1, String value2) {
			addCriterion("co between", value1, value2, "co");
			return (Criteria) this;
		}

		public Criteria andCoNotBetween(String value1, String value2) {
			addCriterion("co not between", value1, value2, "co");
			return (Criteria) this;
		}

		public Criteria andO3IsNull() {
			addCriterion("o3 is null");
			return (Criteria) this;
		}

		public Criteria andO3IsNotNull() {
			addCriterion("o3 is not null");
			return (Criteria) this;
		}

		public Criteria andO3EqualTo(String value) {
			addCriterion("o3 =", value, "o3");
			return (Criteria) this;
		}

		public Criteria andO3NotEqualTo(String value) {
			addCriterion("o3 <>", value, "o3");
			return (Criteria) this;
		}

		public Criteria andO3GreaterThan(String value) {
			addCriterion("o3 >", value, "o3");
			return (Criteria) this;
		}

		public Criteria andO3GreaterThanOrEqualTo(String value) {
			addCriterion("o3 >=", value, "o3");
			return (Criteria) this;
		}

		public Criteria andO3LessThan(String value) {
			addCriterion("o3 <", value, "o3");
			return (Criteria) this;
		}

		public Criteria andO3LessThanOrEqualTo(String value) {
			addCriterion("o3 <=", value, "o3");
			return (Criteria) this;
		}

		public Criteria andO3Like(String value) {
			addCriterion("o3 like", value, "o3");
			return (Criteria) this;
		}

		public Criteria andO3NotLike(String value) {
			addCriterion("o3 not like", value, "o3");
			return (Criteria) this;
		}

		public Criteria andO3In(List<String> values) {
			addCriterion("o3 in", values, "o3");
			return (Criteria) this;
		}

		public Criteria andO3NotIn(List<String> values) {
			addCriterion("o3 not in", values, "o3");
			return (Criteria) this;
		}

		public Criteria andO3Between(String value1, String value2) {
			addCriterion("o3 between", value1, value2, "o3");
			return (Criteria) this;
		}

		public Criteria andO3NotBetween(String value1, String value2) {
			addCriterion("o3 not between", value1, value2, "o3");
			return (Criteria) this;
		}

		public Criteria andSo2IsNull() {
			addCriterion("so2 is null");
			return (Criteria) this;
		}

		public Criteria andSo2IsNotNull() {
			addCriterion("so2 is not null");
			return (Criteria) this;
		}

		public Criteria andSo2EqualTo(String value) {
			addCriterion("so2 =", value, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2NotEqualTo(String value) {
			addCriterion("so2 <>", value, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2GreaterThan(String value) {
			addCriterion("so2 >", value, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2GreaterThanOrEqualTo(String value) {
			addCriterion("so2 >=", value, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2LessThan(String value) {
			addCriterion("so2 <", value, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2LessThanOrEqualTo(String value) {
			addCriterion("so2 <=", value, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2Like(String value) {
			addCriterion("so2 like", value, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2NotLike(String value) {
			addCriterion("so2 not like", value, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2In(List<String> values) {
			addCriterion("so2 in", values, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2NotIn(List<String> values) {
			addCriterion("so2 not in", values, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2Between(String value1, String value2) {
			addCriterion("so2 between", value1, value2, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2NotBetween(String value1, String value2) {
			addCriterion("so2 not between", value1, value2, "so2");
			return (Criteria) this;
		}

		public Criteria andNo2IsNull() {
			addCriterion("no2 is null");
			return (Criteria) this;
		}

		public Criteria andNo2IsNotNull() {
			addCriterion("no2 is not null");
			return (Criteria) this;
		}

		public Criteria andNo2EqualTo(String value) {
			addCriterion("no2 =", value, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2NotEqualTo(String value) {
			addCriterion("no2 <>", value, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2GreaterThan(String value) {
			addCriterion("no2 >", value, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2GreaterThanOrEqualTo(String value) {
			addCriterion("no2 >=", value, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2LessThan(String value) {
			addCriterion("no2 <", value, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2LessThanOrEqualTo(String value) {
			addCriterion("no2 <=", value, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2Like(String value) {
			addCriterion("no2 like", value, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2NotLike(String value) {
			addCriterion("no2 not like", value, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2In(List<String> values) {
			addCriterion("no2 in", values, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2NotIn(List<String> values) {
			addCriterion("no2 not in", values, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2Between(String value1, String value2) {
			addCriterion("no2 between", value1, value2, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2NotBetween(String value1, String value2) {
			addCriterion("no2 not between", value1, value2, "no2");
			return (Criteria) this;
		}

		public Criteria andPm10IsNull() {
			addCriterion("pm10 is null");
			return (Criteria) this;
		}

		public Criteria andPm10IsNotNull() {
			addCriterion("pm10 is not null");
			return (Criteria) this;
		}

		public Criteria andPm10EqualTo(String value) {
			addCriterion("pm10 =", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10NotEqualTo(String value) {
			addCriterion("pm10 <>", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10GreaterThan(String value) {
			addCriterion("pm10 >", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10GreaterThanOrEqualTo(String value) {
			addCriterion("pm10 >=", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10LessThan(String value) {
			addCriterion("pm10 <", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10LessThanOrEqualTo(String value) {
			addCriterion("pm10 <=", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10Like(String value) {
			addCriterion("pm10 like", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10NotLike(String value) {
			addCriterion("pm10 not like", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10In(List<String> values) {
			addCriterion("pm10 in", values, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10NotIn(List<String> values) {
			addCriterion("pm10 not in", values, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10Between(String value1, String value2) {
			addCriterion("pm10 between", value1, value2, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10NotBetween(String value1, String value2) {
			addCriterion("pm10 not between", value1, value2, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm25IsNull() {
			addCriterion("pm25 is null");
			return (Criteria) this;
		}

		public Criteria andPm25IsNotNull() {
			addCriterion("pm25 is not null");
			return (Criteria) this;
		}

		public Criteria andPm25EqualTo(String value) {
			addCriterion("pm25 =", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25NotEqualTo(String value) {
			addCriterion("pm25 <>", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25GreaterThan(String value) {
			addCriterion("pm25 >", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25GreaterThanOrEqualTo(String value) {
			addCriterion("pm25 >=", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25LessThan(String value) {
			addCriterion("pm25 <", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25LessThanOrEqualTo(String value) {
			addCriterion("pm25 <=", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25Like(String value) {
			addCriterion("pm25 like", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25NotLike(String value) {
			addCriterion("pm25 not like", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25In(List<String> values) {
			addCriterion("pm25 in", values, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25NotIn(List<String> values) {
			addCriterion("pm25 not in", values, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25Between(String value1, String value2) {
			addCriterion("pm25 between", value1, value2, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25NotBetween(String value1, String value2) {
			addCriterion("pm25 not between", value1, value2, "pm25");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateEqualTo(Date value) {
			addCriterion("update_date =", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateGreaterThan(Date value) {
			addCriterion("update_date >", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateLessThan(Date value) {
			addCriterion("update_date <", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIn(List<Date> values) {
			addCriterion("update_date in", values, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2,
					"update_date");
			return (Criteria) this;
		}

		public Criteria andNoteIsNull() {
			addCriterion("note is null");
			return (Criteria) this;
		}

		public Criteria andNoteIsNotNull() {
			addCriterion("note is not null");
			return (Criteria) this;
		}

		public Criteria andNoteEqualTo(String value) {
			addCriterion("note =", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotEqualTo(String value) {
			addCriterion("note <>", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThan(String value) {
			addCriterion("note >", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThanOrEqualTo(String value) {
			addCriterion("note >=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThan(String value) {
			addCriterion("note <", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThanOrEqualTo(String value) {
			addCriterion("note <=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLike(String value) {
			addCriterion("note like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotLike(String value) {
			addCriterion("note not like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteIn(List<String> values) {
			addCriterion("note in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotIn(List<String> values) {
			addCriterion("note not in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteBetween(String value1, String value2) {
			addCriterion("note between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotBetween(String value1, String value2) {
			addCriterion("note not between", value1, value2, "note");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pm
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pm
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}