package com.pku.xinfeng.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SensorDataExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	public SensorDataExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andEquip_idIsNull() {
			addCriterion("equip_id is null");
			return (Criteria) this;
		}

		public Criteria andEquip_idIsNotNull() {
			addCriterion("equip_id is not null");
			return (Criteria) this;
		}

		public Criteria andEquip_idEqualTo(String value) {
			addCriterion("equip_id =", value, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idNotEqualTo(String value) {
			addCriterion("equip_id <>", value, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idGreaterThan(String value) {
			addCriterion("equip_id >", value, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idGreaterThanOrEqualTo(String value) {
			addCriterion("equip_id >=", value, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idLessThan(String value) {
			addCriterion("equip_id <", value, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idLessThanOrEqualTo(String value) {
			addCriterion("equip_id <=", value, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idLike(String value) {
			addCriterion("equip_id like", value, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idNotLike(String value) {
			addCriterion("equip_id not like", value, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idIn(List<String> values) {
			addCriterion("equip_id in", values, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idNotIn(List<String> values) {
			addCriterion("equip_id not in", values, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idBetween(String value1, String value2) {
			addCriterion("equip_id between", value1, value2, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idNotBetween(String value1, String value2) {
			addCriterion("equip_id not between", value1, value2, "equip_id");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateEqualTo(Date value) {
			addCriterion("update_date =", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateGreaterThan(Date value) {
			addCriterion("update_date >", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateLessThan(Date value) {
			addCriterion("update_date <", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIn(List<Date> values) {
			addCriterion("update_date in", values, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2,
					"update_date");
			return (Criteria) this;
		}

		public Criteria andPm25IsNull() {
			addCriterion("pm25 is null");
			return (Criteria) this;
		}

		public Criteria andPm25IsNotNull() {
			addCriterion("pm25 is not null");
			return (Criteria) this;
		}

		public Criteria andPm25EqualTo(String value) {
			addCriterion("pm25 =", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25NotEqualTo(String value) {
			addCriterion("pm25 <>", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25GreaterThan(String value) {
			addCriterion("pm25 >", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25GreaterThanOrEqualTo(String value) {
			addCriterion("pm25 >=", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25LessThan(String value) {
			addCriterion("pm25 <", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25LessThanOrEqualTo(String value) {
			addCriterion("pm25 <=", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25Like(String value) {
			addCriterion("pm25 like", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25NotLike(String value) {
			addCriterion("pm25 not like", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25In(List<String> values) {
			addCriterion("pm25 in", values, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25NotIn(List<String> values) {
			addCriterion("pm25 not in", values, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25Between(String value1, String value2) {
			addCriterion("pm25 between", value1, value2, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25NotBetween(String value1, String value2) {
			addCriterion("pm25 not between", value1, value2, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm10IsNull() {
			addCriterion("pm10 is null");
			return (Criteria) this;
		}

		public Criteria andPm10IsNotNull() {
			addCriterion("pm10 is not null");
			return (Criteria) this;
		}

		public Criteria andPm10EqualTo(String value) {
			addCriterion("pm10 =", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10NotEqualTo(String value) {
			addCriterion("pm10 <>", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10GreaterThan(String value) {
			addCriterion("pm10 >", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10GreaterThanOrEqualTo(String value) {
			addCriterion("pm10 >=", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10LessThan(String value) {
			addCriterion("pm10 <", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10LessThanOrEqualTo(String value) {
			addCriterion("pm10 <=", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10Like(String value) {
			addCriterion("pm10 like", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10NotLike(String value) {
			addCriterion("pm10 not like", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10In(List<String> values) {
			addCriterion("pm10 in", values, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10NotIn(List<String> values) {
			addCriterion("pm10 not in", values, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10Between(String value1, String value2) {
			addCriterion("pm10 between", value1, value2, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10NotBetween(String value1, String value2) {
			addCriterion("pm10 not between", value1, value2, "pm10");
			return (Criteria) this;
		}

		public Criteria andCo2IsNull() {
			addCriterion("co2 is null");
			return (Criteria) this;
		}

		public Criteria andCo2IsNotNull() {
			addCriterion("co2 is not null");
			return (Criteria) this;
		}

		public Criteria andCo2EqualTo(String value) {
			addCriterion("co2 =", value, "co2");
			return (Criteria) this;
		}

		public Criteria andCo2NotEqualTo(String value) {
			addCriterion("co2 <>", value, "co2");
			return (Criteria) this;
		}

		public Criteria andCo2GreaterThan(String value) {
			addCriterion("co2 >", value, "co2");
			return (Criteria) this;
		}

		public Criteria andCo2GreaterThanOrEqualTo(String value) {
			addCriterion("co2 >=", value, "co2");
			return (Criteria) this;
		}

		public Criteria andCo2LessThan(String value) {
			addCriterion("co2 <", value, "co2");
			return (Criteria) this;
		}

		public Criteria andCo2LessThanOrEqualTo(String value) {
			addCriterion("co2 <=", value, "co2");
			return (Criteria) this;
		}

		public Criteria andCo2Like(String value) {
			addCriterion("co2 like", value, "co2");
			return (Criteria) this;
		}

		public Criteria andCo2NotLike(String value) {
			addCriterion("co2 not like", value, "co2");
			return (Criteria) this;
		}

		public Criteria andCo2In(List<String> values) {
			addCriterion("co2 in", values, "co2");
			return (Criteria) this;
		}

		public Criteria andCo2NotIn(List<String> values) {
			addCriterion("co2 not in", values, "co2");
			return (Criteria) this;
		}

		public Criteria andCo2Between(String value1, String value2) {
			addCriterion("co2 between", value1, value2, "co2");
			return (Criteria) this;
		}

		public Criteria andCo2NotBetween(String value1, String value2) {
			addCriterion("co2 not between", value1, value2, "co2");
			return (Criteria) this;
		}

		public Criteria andVocIsNull() {
			addCriterion("voc is null");
			return (Criteria) this;
		}

		public Criteria andVocIsNotNull() {
			addCriterion("voc is not null");
			return (Criteria) this;
		}

		public Criteria andVocEqualTo(String value) {
			addCriterion("voc =", value, "voc");
			return (Criteria) this;
		}

		public Criteria andVocNotEqualTo(String value) {
			addCriterion("voc <>", value, "voc");
			return (Criteria) this;
		}

		public Criteria andVocGreaterThan(String value) {
			addCriterion("voc >", value, "voc");
			return (Criteria) this;
		}

		public Criteria andVocGreaterThanOrEqualTo(String value) {
			addCriterion("voc >=", value, "voc");
			return (Criteria) this;
		}

		public Criteria andVocLessThan(String value) {
			addCriterion("voc <", value, "voc");
			return (Criteria) this;
		}

		public Criteria andVocLessThanOrEqualTo(String value) {
			addCriterion("voc <=", value, "voc");
			return (Criteria) this;
		}

		public Criteria andVocLike(String value) {
			addCriterion("voc like", value, "voc");
			return (Criteria) this;
		}

		public Criteria andVocNotLike(String value) {
			addCriterion("voc not like", value, "voc");
			return (Criteria) this;
		}

		public Criteria andVocIn(List<String> values) {
			addCriterion("voc in", values, "voc");
			return (Criteria) this;
		}

		public Criteria andVocNotIn(List<String> values) {
			addCriterion("voc not in", values, "voc");
			return (Criteria) this;
		}

		public Criteria andVocBetween(String value1, String value2) {
			addCriterion("voc between", value1, value2, "voc");
			return (Criteria) this;
		}

		public Criteria andVocNotBetween(String value1, String value2) {
			addCriterion("voc not between", value1, value2, "voc");
			return (Criteria) this;
		}

		public Criteria andMethanolIsNull() {
			addCriterion("methanol is null");
			return (Criteria) this;
		}

		public Criteria andMethanolIsNotNull() {
			addCriterion("methanol is not null");
			return (Criteria) this;
		}

		public Criteria andMethanolEqualTo(String value) {
			addCriterion("methanol =", value, "methanol");
			return (Criteria) this;
		}

		public Criteria andMethanolNotEqualTo(String value) {
			addCriterion("methanol <>", value, "methanol");
			return (Criteria) this;
		}

		public Criteria andMethanolGreaterThan(String value) {
			addCriterion("methanol >", value, "methanol");
			return (Criteria) this;
		}

		public Criteria andMethanolGreaterThanOrEqualTo(String value) {
			addCriterion("methanol >=", value, "methanol");
			return (Criteria) this;
		}

		public Criteria andMethanolLessThan(String value) {
			addCriterion("methanol <", value, "methanol");
			return (Criteria) this;
		}

		public Criteria andMethanolLessThanOrEqualTo(String value) {
			addCriterion("methanol <=", value, "methanol");
			return (Criteria) this;
		}

		public Criteria andMethanolLike(String value) {
			addCriterion("methanol like", value, "methanol");
			return (Criteria) this;
		}

		public Criteria andMethanolNotLike(String value) {
			addCriterion("methanol not like", value, "methanol");
			return (Criteria) this;
		}

		public Criteria andMethanolIn(List<String> values) {
			addCriterion("methanol in", values, "methanol");
			return (Criteria) this;
		}

		public Criteria andMethanolNotIn(List<String> values) {
			addCriterion("methanol not in", values, "methanol");
			return (Criteria) this;
		}

		public Criteria andMethanolBetween(String value1, String value2) {
			addCriterion("methanol between", value1, value2, "methanol");
			return (Criteria) this;
		}

		public Criteria andMethanolNotBetween(String value1, String value2) {
			addCriterion("methanol not between", value1, value2, "methanol");
			return (Criteria) this;
		}

		public Criteria andTemperatureIsNull() {
			addCriterion("temperature is null");
			return (Criteria) this;
		}

		public Criteria andTemperatureIsNotNull() {
			addCriterion("temperature is not null");
			return (Criteria) this;
		}

		public Criteria andTemperatureEqualTo(String value) {
			addCriterion("temperature =", value, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureNotEqualTo(String value) {
			addCriterion("temperature <>", value, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureGreaterThan(String value) {
			addCriterion("temperature >", value, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureGreaterThanOrEqualTo(String value) {
			addCriterion("temperature >=", value, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureLessThan(String value) {
			addCriterion("temperature <", value, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureLessThanOrEqualTo(String value) {
			addCriterion("temperature <=", value, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureLike(String value) {
			addCriterion("temperature like", value, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureNotLike(String value) {
			addCriterion("temperature not like", value, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureIn(List<String> values) {
			addCriterion("temperature in", values, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureNotIn(List<String> values) {
			addCriterion("temperature not in", values, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureBetween(String value1, String value2) {
			addCriterion("temperature between", value1, value2, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureNotBetween(String value1, String value2) {
			addCriterion("temperature not between", value1, value2,
					"temperature");
			return (Criteria) this;
		}

		public Criteria andHumidityIsNull() {
			addCriterion("humidity is null");
			return (Criteria) this;
		}

		public Criteria andHumidityIsNotNull() {
			addCriterion("humidity is not null");
			return (Criteria) this;
		}

		public Criteria andHumidityEqualTo(String value) {
			addCriterion("humidity =", value, "humidity");
			return (Criteria) this;
		}

		public Criteria andHumidityNotEqualTo(String value) {
			addCriterion("humidity <>", value, "humidity");
			return (Criteria) this;
		}

		public Criteria andHumidityGreaterThan(String value) {
			addCriterion("humidity >", value, "humidity");
			return (Criteria) this;
		}

		public Criteria andHumidityGreaterThanOrEqualTo(String value) {
			addCriterion("humidity >=", value, "humidity");
			return (Criteria) this;
		}

		public Criteria andHumidityLessThan(String value) {
			addCriterion("humidity <", value, "humidity");
			return (Criteria) this;
		}

		public Criteria andHumidityLessThanOrEqualTo(String value) {
			addCriterion("humidity <=", value, "humidity");
			return (Criteria) this;
		}

		public Criteria andHumidityLike(String value) {
			addCriterion("humidity like", value, "humidity");
			return (Criteria) this;
		}

		public Criteria andHumidityNotLike(String value) {
			addCriterion("humidity not like", value, "humidity");
			return (Criteria) this;
		}

		public Criteria andHumidityIn(List<String> values) {
			addCriterion("humidity in", values, "humidity");
			return (Criteria) this;
		}

		public Criteria andHumidityNotIn(List<String> values) {
			addCriterion("humidity not in", values, "humidity");
			return (Criteria) this;
		}

		public Criteria andHumidityBetween(String value1, String value2) {
			addCriterion("humidity between", value1, value2, "humidity");
			return (Criteria) this;
		}

		public Criteria andHumidityNotBetween(String value1, String value2) {
			addCriterion("humidity not between", value1, value2, "humidity");
			return (Criteria) this;
		}

		public Criteria andStrainerIsNull() {
			addCriterion("strainer is null");
			return (Criteria) this;
		}

		public Criteria andStrainerIsNotNull() {
			addCriterion("strainer is not null");
			return (Criteria) this;
		}

		public Criteria andStrainerEqualTo(String value) {
			addCriterion("strainer =", value, "strainer");
			return (Criteria) this;
		}

		public Criteria andStrainerNotEqualTo(String value) {
			addCriterion("strainer <>", value, "strainer");
			return (Criteria) this;
		}

		public Criteria andStrainerGreaterThan(String value) {
			addCriterion("strainer >", value, "strainer");
			return (Criteria) this;
		}

		public Criteria andStrainerGreaterThanOrEqualTo(String value) {
			addCriterion("strainer >=", value, "strainer");
			return (Criteria) this;
		}

		public Criteria andStrainerLessThan(String value) {
			addCriterion("strainer <", value, "strainer");
			return (Criteria) this;
		}

		public Criteria andStrainerLessThanOrEqualTo(String value) {
			addCriterion("strainer <=", value, "strainer");
			return (Criteria) this;
		}

		public Criteria andStrainerLike(String value) {
			addCriterion("strainer like", value, "strainer");
			return (Criteria) this;
		}

		public Criteria andStrainerNotLike(String value) {
			addCriterion("strainer not like", value, "strainer");
			return (Criteria) this;
		}

		public Criteria andStrainerIn(List<String> values) {
			addCriterion("strainer in", values, "strainer");
			return (Criteria) this;
		}

		public Criteria andStrainerNotIn(List<String> values) {
			addCriterion("strainer not in", values, "strainer");
			return (Criteria) this;
		}

		public Criteria andStrainerBetween(String value1, String value2) {
			addCriterion("strainer between", value1, value2, "strainer");
			return (Criteria) this;
		}

		public Criteria andStrainerNotBetween(String value1, String value2) {
			addCriterion("strainer not between", value1, value2, "strainer");
			return (Criteria) this;
		}

		public Criteria andNoteIsNull() {
			addCriterion("note is null");
			return (Criteria) this;
		}

		public Criteria andNoteIsNotNull() {
			addCriterion("note is not null");
			return (Criteria) this;
		}

		public Criteria andNoteEqualTo(String value) {
			addCriterion("note =", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotEqualTo(String value) {
			addCriterion("note <>", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThan(String value) {
			addCriterion("note >", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThanOrEqualTo(String value) {
			addCriterion("note >=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThan(String value) {
			addCriterion("note <", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThanOrEqualTo(String value) {
			addCriterion("note <=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLike(String value) {
			addCriterion("note like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotLike(String value) {
			addCriterion("note not like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteIn(List<String> values) {
			addCriterion("note in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotIn(List<String> values) {
			addCriterion("note not in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteBetween(String value1, String value2) {
			addCriterion("note between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotBetween(String value1, String value2) {
			addCriterion("note not between", value1, value2, "note");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sensor_data
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sensor_data
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}