package com.pku.xinfeng.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TemperatureExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table temperature
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table temperature
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table temperature
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	public TemperatureExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table temperature
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table temperature
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCityIdIsNull() {
			addCriterion("cityId is null");
			return (Criteria) this;
		}

		public Criteria andCityIdIsNotNull() {
			addCriterion("cityId is not null");
			return (Criteria) this;
		}

		public Criteria andCityIdEqualTo(String value) {
			addCriterion("cityId =", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotEqualTo(String value) {
			addCriterion("cityId <>", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdGreaterThan(String value) {
			addCriterion("cityId >", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdGreaterThanOrEqualTo(String value) {
			addCriterion("cityId >=", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdLessThan(String value) {
			addCriterion("cityId <", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdLessThanOrEqualTo(String value) {
			addCriterion("cityId <=", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdLike(String value) {
			addCriterion("cityId like", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotLike(String value) {
			addCriterion("cityId not like", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdIn(List<String> values) {
			addCriterion("cityId in", values, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotIn(List<String> values) {
			addCriterion("cityId not in", values, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdBetween(String value1, String value2) {
			addCriterion("cityId between", value1, value2, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotBetween(String value1, String value2) {
			addCriterion("cityId not between", value1, value2, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityNameIsNull() {
			addCriterion("cityName is null");
			return (Criteria) this;
		}

		public Criteria andCityNameIsNotNull() {
			addCriterion("cityName is not null");
			return (Criteria) this;
		}

		public Criteria andCityNameEqualTo(String value) {
			addCriterion("cityName =", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameNotEqualTo(String value) {
			addCriterion("cityName <>", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameGreaterThan(String value) {
			addCriterion("cityName >", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameGreaterThanOrEqualTo(String value) {
			addCriterion("cityName >=", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameLessThan(String value) {
			addCriterion("cityName <", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameLessThanOrEqualTo(String value) {
			addCriterion("cityName <=", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameLike(String value) {
			addCriterion("cityName like", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameNotLike(String value) {
			addCriterion("cityName not like", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameIn(List<String> values) {
			addCriterion("cityName in", values, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameNotIn(List<String> values) {
			addCriterion("cityName not in", values, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameBetween(String value1, String value2) {
			addCriterion("cityName between", value1, value2, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameNotBetween(String value1, String value2) {
			addCriterion("cityName not between", value1, value2, "cityName");
			return (Criteria) this;
		}

		public Criteria andWind_directionIsNull() {
			addCriterion("wind_direction is null");
			return (Criteria) this;
		}

		public Criteria andWind_directionIsNotNull() {
			addCriterion("wind_direction is not null");
			return (Criteria) this;
		}

		public Criteria andWind_directionEqualTo(String value) {
			addCriterion("wind_direction =", value, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionNotEqualTo(String value) {
			addCriterion("wind_direction <>", value, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionGreaterThan(String value) {
			addCriterion("wind_direction >", value, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionGreaterThanOrEqualTo(String value) {
			addCriterion("wind_direction >=", value, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionLessThan(String value) {
			addCriterion("wind_direction <", value, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionLessThanOrEqualTo(String value) {
			addCriterion("wind_direction <=", value, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionLike(String value) {
			addCriterion("wind_direction like", value, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionNotLike(String value) {
			addCriterion("wind_direction not like", value, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionIn(List<String> values) {
			addCriterion("wind_direction in", values, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionNotIn(List<String> values) {
			addCriterion("wind_direction not in", values, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionBetween(String value1, String value2) {
			addCriterion("wind_direction between", value1, value2,
					"wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionNotBetween(String value1, String value2) {
			addCriterion("wind_direction not between", value1, value2,
					"wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_forceIsNull() {
			addCriterion("wind_force is null");
			return (Criteria) this;
		}

		public Criteria andWind_forceIsNotNull() {
			addCriterion("wind_force is not null");
			return (Criteria) this;
		}

		public Criteria andWind_forceEqualTo(String value) {
			addCriterion("wind_force =", value, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceNotEqualTo(String value) {
			addCriterion("wind_force <>", value, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceGreaterThan(String value) {
			addCriterion("wind_force >", value, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceGreaterThanOrEqualTo(String value) {
			addCriterion("wind_force >=", value, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceLessThan(String value) {
			addCriterion("wind_force <", value, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceLessThanOrEqualTo(String value) {
			addCriterion("wind_force <=", value, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceLike(String value) {
			addCriterion("wind_force like", value, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceNotLike(String value) {
			addCriterion("wind_force not like", value, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceIn(List<String> values) {
			addCriterion("wind_force in", values, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceNotIn(List<String> values) {
			addCriterion("wind_force not in", values, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceBetween(String value1, String value2) {
			addCriterion("wind_force between", value1, value2, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceNotBetween(String value1, String value2) {
			addCriterion("wind_force not between", value1, value2, "wind_force");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayIsNull() {
			addCriterion("temperature_day is null");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayIsNotNull() {
			addCriterion("temperature_day is not null");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayEqualTo(String value) {
			addCriterion("temperature_day =", value, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayNotEqualTo(String value) {
			addCriterion("temperature_day <>", value, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayGreaterThan(String value) {
			addCriterion("temperature_day >", value, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayGreaterThanOrEqualTo(String value) {
			addCriterion("temperature_day >=", value, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayLessThan(String value) {
			addCriterion("temperature_day <", value, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayLessThanOrEqualTo(String value) {
			addCriterion("temperature_day <=", value, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayLike(String value) {
			addCriterion("temperature_day like", value, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayNotLike(String value) {
			addCriterion("temperature_day not like", value, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayIn(List<String> values) {
			addCriterion("temperature_day in", values, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayNotIn(List<String> values) {
			addCriterion("temperature_day not in", values, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayBetween(String value1, String value2) {
			addCriterion("temperature_day between", value1, value2,
					"temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayNotBetween(String value1,
				String value2) {
			addCriterion("temperature_day not between", value1, value2,
					"temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightIsNull() {
			addCriterion("temperature_night is null");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightIsNotNull() {
			addCriterion("temperature_night is not null");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightEqualTo(String value) {
			addCriterion("temperature_night =", value, "temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightNotEqualTo(String value) {
			addCriterion("temperature_night <>", value, "temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightGreaterThan(String value) {
			addCriterion("temperature_night >", value, "temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightGreaterThanOrEqualTo(String value) {
			addCriterion("temperature_night >=", value, "temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightLessThan(String value) {
			addCriterion("temperature_night <", value, "temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightLessThanOrEqualTo(String value) {
			addCriterion("temperature_night <=", value, "temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightLike(String value) {
			addCriterion("temperature_night like", value, "temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightNotLike(String value) {
			addCriterion("temperature_night not like", value,
					"temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightIn(List<String> values) {
			addCriterion("temperature_night in", values, "temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightNotIn(List<String> values) {
			addCriterion("temperature_night not in", values,
					"temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightBetween(String value1, String value2) {
			addCriterion("temperature_night between", value1, value2,
					"temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightNotBetween(String value1,
				String value2) {
			addCriterion("temperature_night not between", value1, value2,
					"temperature_night");
			return (Criteria) this;
		}

		public Criteria andWeather_typeIsNull() {
			addCriterion("weather_type is null");
			return (Criteria) this;
		}

		public Criteria andWeather_typeIsNotNull() {
			addCriterion("weather_type is not null");
			return (Criteria) this;
		}

		public Criteria andWeather_typeEqualTo(String value) {
			addCriterion("weather_type =", value, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeNotEqualTo(String value) {
			addCriterion("weather_type <>", value, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeGreaterThan(String value) {
			addCriterion("weather_type >", value, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeGreaterThanOrEqualTo(String value) {
			addCriterion("weather_type >=", value, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeLessThan(String value) {
			addCriterion("weather_type <", value, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeLessThanOrEqualTo(String value) {
			addCriterion("weather_type <=", value, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeLike(String value) {
			addCriterion("weather_type like", value, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeNotLike(String value) {
			addCriterion("weather_type not like", value, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeIn(List<String> values) {
			addCriterion("weather_type in", values, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeNotIn(List<String> values) {
			addCriterion("weather_type not in", values, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeBetween(String value1, String value2) {
			addCriterion("weather_type between", value1, value2, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeNotBetween(String value1, String value2) {
			addCriterion("weather_type not between", value1, value2,
					"weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameIsNull() {
			addCriterion("weather_type_name is null");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameIsNotNull() {
			addCriterion("weather_type_name is not null");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameEqualTo(String value) {
			addCriterion("weather_type_name =", value, "weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameNotEqualTo(String value) {
			addCriterion("weather_type_name <>", value, "weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameGreaterThan(String value) {
			addCriterion("weather_type_name >", value, "weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameGreaterThanOrEqualTo(String value) {
			addCriterion("weather_type_name >=", value, "weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameLessThan(String value) {
			addCriterion("weather_type_name <", value, "weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameLessThanOrEqualTo(String value) {
			addCriterion("weather_type_name <=", value, "weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameLike(String value) {
			addCriterion("weather_type_name like", value, "weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameNotLike(String value) {
			addCriterion("weather_type_name not like", value,
					"weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameIn(List<String> values) {
			addCriterion("weather_type_name in", values, "weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameNotIn(List<String> values) {
			addCriterion("weather_type_name not in", values,
					"weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameBetween(String value1, String value2) {
			addCriterion("weather_type_name between", value1, value2,
					"weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameNotBetween(String value1,
				String value2) {
			addCriterion("weather_type_name not between", value1, value2,
					"weather_type_name");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateEqualTo(Date value) {
			addCriterion("update_date =", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateGreaterThan(Date value) {
			addCriterion("update_date >", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateLessThan(Date value) {
			addCriterion("update_date <", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIn(List<Date> values) {
			addCriterion("update_date in", values, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2,
					"update_date");
			return (Criteria) this;
		}

		public Criteria andNoteIsNull() {
			addCriterion("note is null");
			return (Criteria) this;
		}

		public Criteria andNoteIsNotNull() {
			addCriterion("note is not null");
			return (Criteria) this;
		}

		public Criteria andNoteEqualTo(String value) {
			addCriterion("note =", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotEqualTo(String value) {
			addCriterion("note <>", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThan(String value) {
			addCriterion("note >", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThanOrEqualTo(String value) {
			addCriterion("note >=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThan(String value) {
			addCriterion("note <", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThanOrEqualTo(String value) {
			addCriterion("note <=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLike(String value) {
			addCriterion("note like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotLike(String value) {
			addCriterion("note not like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteIn(List<String> values) {
			addCriterion("note in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotIn(List<String> values) {
			addCriterion("note not in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteBetween(String value1, String value2) {
			addCriterion("note between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotBetween(String value1, String value2) {
			addCriterion("note not between", value1, value2, "note");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table temperature
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table temperature
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}