package com.pku.xinfeng.model;

import java.util.Date;

public class UserEquipment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_equipment.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_equipment.user_id
	 * @mbggenerated
	 */
	private String user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_equipment.equip_id
	 * @mbggenerated
	 */
	private String equip_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_equipment.equip_name
	 * @mbggenerated
	 */
	private String equip_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_equipment.add_position
	 * @mbggenerated
	 */
	private String add_position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_equipment.update_date
	 * @mbggenerated
	 */
	private Date update_date;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_equipment.id
	 * @return  the value of user_equipment.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_equipment.id
	 * @param id  the value for user_equipment.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_equipment.user_id
	 * @return  the value of user_equipment.user_id
	 * @mbggenerated
	 */
	public String getUser_id() {
		return user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_equipment.user_id
	 * @param user_id  the value for user_equipment.user_id
	 * @mbggenerated
	 */
	public void setUser_id(String user_id) {
		this.user_id = user_id == null ? null : user_id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_equipment.equip_id
	 * @return  the value of user_equipment.equip_id
	 * @mbggenerated
	 */
	public String getEquip_id() {
		return equip_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_equipment.equip_id
	 * @param equip_id  the value for user_equipment.equip_id
	 * @mbggenerated
	 */
	public void setEquip_id(String equip_id) {
		this.equip_id = equip_id == null ? null : equip_id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_equipment.equip_name
	 * @return  the value of user_equipment.equip_name
	 * @mbggenerated
	 */
	public String getEquip_name() {
		return equip_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_equipment.equip_name
	 * @param equip_name  the value for user_equipment.equip_name
	 * @mbggenerated
	 */
	public void setEquip_name(String equip_name) {
		this.equip_name = equip_name == null ? null : equip_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_equipment.add_position
	 * @return  the value of user_equipment.add_position
	 * @mbggenerated
	 */
	public String getAdd_position() {
		return add_position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_equipment.add_position
	 * @param add_position  the value for user_equipment.add_position
	 * @mbggenerated
	 */
	public void setAdd_position(String add_position) {
		this.add_position = add_position == null ? null : add_position.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_equipment.update_date
	 * @return  the value of user_equipment.update_date
	 * @mbggenerated
	 */
	public Date getUpdate_date() {
		return update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_equipment.update_date
	 * @param update_date  the value for user_equipment.update_date
	 * @mbggenerated
	 */
	public void setUpdate_date(Date update_date) {
		this.update_date = update_date;
	}
}