package com.pku.xinfeng.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserEquipmentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	public UserEquipmentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUser_idIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUser_idIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUser_idEqualTo(String value) {
			addCriterion("user_id =", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotEqualTo(String value) {
			addCriterion("user_id <>", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idGreaterThan(String value) {
			addCriterion("user_id >", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idLessThan(String value) {
			addCriterion("user_id <", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idLike(String value) {
			addCriterion("user_id like", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotLike(String value) {
			addCriterion("user_id not like", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idIn(List<String> values) {
			addCriterion("user_id in", values, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotIn(List<String> values) {
			addCriterion("user_id not in", values, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "user_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idIsNull() {
			addCriterion("equip_id is null");
			return (Criteria) this;
		}

		public Criteria andEquip_idIsNotNull() {
			addCriterion("equip_id is not null");
			return (Criteria) this;
		}

		public Criteria andEquip_idEqualTo(String value) {
			addCriterion("equip_id =", value, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idNotEqualTo(String value) {
			addCriterion("equip_id <>", value, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idGreaterThan(String value) {
			addCriterion("equip_id >", value, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idGreaterThanOrEqualTo(String value) {
			addCriterion("equip_id >=", value, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idLessThan(String value) {
			addCriterion("equip_id <", value, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idLessThanOrEqualTo(String value) {
			addCriterion("equip_id <=", value, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idLike(String value) {
			addCriterion("equip_id like", value, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idNotLike(String value) {
			addCriterion("equip_id not like", value, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idIn(List<String> values) {
			addCriterion("equip_id in", values, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idNotIn(List<String> values) {
			addCriterion("equip_id not in", values, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idBetween(String value1, String value2) {
			addCriterion("equip_id between", value1, value2, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_idNotBetween(String value1, String value2) {
			addCriterion("equip_id not between", value1, value2, "equip_id");
			return (Criteria) this;
		}

		public Criteria andEquip_nameIsNull() {
			addCriterion("equip_name is null");
			return (Criteria) this;
		}

		public Criteria andEquip_nameIsNotNull() {
			addCriterion("equip_name is not null");
			return (Criteria) this;
		}

		public Criteria andEquip_nameEqualTo(String value) {
			addCriterion("equip_name =", value, "equip_name");
			return (Criteria) this;
		}

		public Criteria andEquip_nameNotEqualTo(String value) {
			addCriterion("equip_name <>", value, "equip_name");
			return (Criteria) this;
		}

		public Criteria andEquip_nameGreaterThan(String value) {
			addCriterion("equip_name >", value, "equip_name");
			return (Criteria) this;
		}

		public Criteria andEquip_nameGreaterThanOrEqualTo(String value) {
			addCriterion("equip_name >=", value, "equip_name");
			return (Criteria) this;
		}

		public Criteria andEquip_nameLessThan(String value) {
			addCriterion("equip_name <", value, "equip_name");
			return (Criteria) this;
		}

		public Criteria andEquip_nameLessThanOrEqualTo(String value) {
			addCriterion("equip_name <=", value, "equip_name");
			return (Criteria) this;
		}

		public Criteria andEquip_nameLike(String value) {
			addCriterion("equip_name like", value, "equip_name");
			return (Criteria) this;
		}

		public Criteria andEquip_nameNotLike(String value) {
			addCriterion("equip_name not like", value, "equip_name");
			return (Criteria) this;
		}

		public Criteria andEquip_nameIn(List<String> values) {
			addCriterion("equip_name in", values, "equip_name");
			return (Criteria) this;
		}

		public Criteria andEquip_nameNotIn(List<String> values) {
			addCriterion("equip_name not in", values, "equip_name");
			return (Criteria) this;
		}

		public Criteria andEquip_nameBetween(String value1, String value2) {
			addCriterion("equip_name between", value1, value2, "equip_name");
			return (Criteria) this;
		}

		public Criteria andEquip_nameNotBetween(String value1, String value2) {
			addCriterion("equip_name not between", value1, value2, "equip_name");
			return (Criteria) this;
		}

		public Criteria andAdd_positionIsNull() {
			addCriterion("add_position is null");
			return (Criteria) this;
		}

		public Criteria andAdd_positionIsNotNull() {
			addCriterion("add_position is not null");
			return (Criteria) this;
		}

		public Criteria andAdd_positionEqualTo(String value) {
			addCriterion("add_position =", value, "add_position");
			return (Criteria) this;
		}

		public Criteria andAdd_positionNotEqualTo(String value) {
			addCriterion("add_position <>", value, "add_position");
			return (Criteria) this;
		}

		public Criteria andAdd_positionGreaterThan(String value) {
			addCriterion("add_position >", value, "add_position");
			return (Criteria) this;
		}

		public Criteria andAdd_positionGreaterThanOrEqualTo(String value) {
			addCriterion("add_position >=", value, "add_position");
			return (Criteria) this;
		}

		public Criteria andAdd_positionLessThan(String value) {
			addCriterion("add_position <", value, "add_position");
			return (Criteria) this;
		}

		public Criteria andAdd_positionLessThanOrEqualTo(String value) {
			addCriterion("add_position <=", value, "add_position");
			return (Criteria) this;
		}

		public Criteria andAdd_positionLike(String value) {
			addCriterion("add_position like", value, "add_position");
			return (Criteria) this;
		}

		public Criteria andAdd_positionNotLike(String value) {
			addCriterion("add_position not like", value, "add_position");
			return (Criteria) this;
		}

		public Criteria andAdd_positionIn(List<String> values) {
			addCriterion("add_position in", values, "add_position");
			return (Criteria) this;
		}

		public Criteria andAdd_positionNotIn(List<String> values) {
			addCriterion("add_position not in", values, "add_position");
			return (Criteria) this;
		}

		public Criteria andAdd_positionBetween(String value1, String value2) {
			addCriterion("add_position between", value1, value2, "add_position");
			return (Criteria) this;
		}

		public Criteria andAdd_positionNotBetween(String value1, String value2) {
			addCriterion("add_position not between", value1, value2,
					"add_position");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateEqualTo(Date value) {
			addCriterion("update_date =", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateGreaterThan(Date value) {
			addCriterion("update_date >", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateLessThan(Date value) {
			addCriterion("update_date <", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIn(List<Date> values) {
			addCriterion("update_date in", values, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2,
					"update_date");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_equipment
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_equipment
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}