package com.pku.xinfeng.model;

import java.util.Date;

public class UserWeather {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_weather.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_weather.user_id
	 * @mbggenerated
	 */
	private String user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_weather.city
	 * @mbggenerated
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_weather.update_date
	 * @mbggenerated
	 */
	private Date update_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_weather.note
	 * @mbggenerated
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_weather.id
	 * @return  the value of user_weather.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_weather.id
	 * @param id  the value for user_weather.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_weather.user_id
	 * @return  the value of user_weather.user_id
	 * @mbggenerated
	 */
	public String getUser_id() {
		return user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_weather.user_id
	 * @param user_id  the value for user_weather.user_id
	 * @mbggenerated
	 */
	public void setUser_id(String user_id) {
		this.user_id = user_id == null ? null : user_id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_weather.city
	 * @return  the value of user_weather.city
	 * @mbggenerated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_weather.city
	 * @param city  the value for user_weather.city
	 * @mbggenerated
	 */
	public void setCity(String city) {
		this.city = city == null ? null : city.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_weather.update_date
	 * @return  the value of user_weather.update_date
	 * @mbggenerated
	 */
	public Date getUpdate_date() {
		return update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_weather.update_date
	 * @param update_date  the value for user_weather.update_date
	 * @mbggenerated
	 */
	public void setUpdate_date(Date update_date) {
		this.update_date = update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_weather.note
	 * @return  the value of user_weather.note
	 * @mbggenerated
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_weather.note
	 * @param note  the value for user_weather.note
	 * @mbggenerated
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}
}