package com.pku.xinfeng.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbggenerated
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.mail
	 * @mbggenerated
	 */
	private String mail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.qq
	 * @mbggenerated
	 */
	private String qq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.address
	 * @mbggenerated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.wechat
	 * @mbggenerated
	 */
	private String wechat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.update_date
	 * @mbggenerated
	 */
	private Date update_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.isAdmin
	 * @mbggenerated
	 */
	private String isAdmin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.note
	 * @mbggenerated
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbggenerated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbggenerated
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
	 * @return  the value of user.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
	 * @param phone  the value for user.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.mail
	 * @return  the value of user.mail
	 * @mbggenerated
	 */
	public String getMail() {
		return mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.mail
	 * @param mail  the value for user.mail
	 * @mbggenerated
	 */
	public void setMail(String mail) {
		this.mail = mail == null ? null : mail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.qq
	 * @return  the value of user.qq
	 * @mbggenerated
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.qq
	 * @param qq  the value for user.qq
	 * @mbggenerated
	 */
	public void setQq(String qq) {
		this.qq = qq == null ? null : qq.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.address
	 * @return  the value of user.address
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.address
	 * @param address  the value for user.address
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.wechat
	 * @return  the value of user.wechat
	 * @mbggenerated
	 */
	public String getWechat() {
		return wechat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.wechat
	 * @param wechat  the value for user.wechat
	 * @mbggenerated
	 */
	public void setWechat(String wechat) {
		this.wechat = wechat == null ? null : wechat.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.update_date
	 * @return  the value of user.update_date
	 * @mbggenerated
	 */
	public Date getUpdate_date() {
		return update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.update_date
	 * @param update_date  the value for user.update_date
	 * @mbggenerated
	 */
	public void setUpdate_date(Date update_date) {
		this.update_date = update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.isAdmin
	 * @return  the value of user.isAdmin
	 * @mbggenerated
	 */
	public String getIsAdmin() {
		return isAdmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.isAdmin
	 * @param isAdmin  the value for user.isAdmin
	 * @mbggenerated
	 */
	public void setIsAdmin(String isAdmin) {
		this.isAdmin = isAdmin == null ? null : isAdmin.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.note
	 * @return  the value of user.note
	 * @mbggenerated
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.note
	 * @param note  the value for user.note
	 * @mbggenerated
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}
}