package com.pku.xinfeng.model;

import java.util.Date;

public class Version {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column version.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column version.version
	 * @mbggenerated
	 */
	private String version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column version.commands
	 * @mbggenerated
	 */
	private String commands;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column version.update_date
	 * @mbggenerated
	 */
	private Date update_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column version.note
	 * @mbggenerated
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column version.id
	 * @return  the value of version.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column version.id
	 * @param id  the value for version.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column version.version
	 * @return  the value of version.version
	 * @mbggenerated
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column version.version
	 * @param version  the value for version.version
	 * @mbggenerated
	 */
	public void setVersion(String version) {
		this.version = version == null ? null : version.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column version.commands
	 * @return  the value of version.commands
	 * @mbggenerated
	 */
	public String getCommands() {
		return commands;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column version.commands
	 * @param commands  the value for version.commands
	 * @mbggenerated
	 */
	public void setCommands(String commands) {
		this.commands = commands == null ? null : commands.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column version.update_date
	 * @return  the value of version.update_date
	 * @mbggenerated
	 */
	public Date getUpdate_date() {
		return update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column version.update_date
	 * @param update_date  the value for version.update_date
	 * @mbggenerated
	 */
	public void setUpdate_date(Date update_date) {
		this.update_date = update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column version.note
	 * @return  the value of version.note
	 * @mbggenerated
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column version.note
	 * @param note  the value for version.note
	 * @mbggenerated
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}
}