package com.pku.xinfeng.model;

import java.util.ArrayList;
import java.util.List;

public class WeatherExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table weather
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table weather
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table weather
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	public WeatherExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table weather
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table weather
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCityIdIsNull() {
			addCriterion("cityId is null");
			return (Criteria) this;
		}

		public Criteria andCityIdIsNotNull() {
			addCriterion("cityId is not null");
			return (Criteria) this;
		}

		public Criteria andCityIdEqualTo(String value) {
			addCriterion("cityId =", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotEqualTo(String value) {
			addCriterion("cityId <>", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdGreaterThan(String value) {
			addCriterion("cityId >", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdGreaterThanOrEqualTo(String value) {
			addCriterion("cityId >=", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdLessThan(String value) {
			addCriterion("cityId <", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdLessThanOrEqualTo(String value) {
			addCriterion("cityId <=", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdLike(String value) {
			addCriterion("cityId like", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotLike(String value) {
			addCriterion("cityId not like", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdIn(List<String> values) {
			addCriterion("cityId in", values, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotIn(List<String> values) {
			addCriterion("cityId not in", values, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdBetween(String value1, String value2) {
			addCriterion("cityId between", value1, value2, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotBetween(String value1, String value2) {
			addCriterion("cityId not between", value1, value2, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityNameIsNull() {
			addCriterion("cityName is null");
			return (Criteria) this;
		}

		public Criteria andCityNameIsNotNull() {
			addCriterion("cityName is not null");
			return (Criteria) this;
		}

		public Criteria andCityNameEqualTo(String value) {
			addCriterion("cityName =", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameNotEqualTo(String value) {
			addCriterion("cityName <>", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameGreaterThan(String value) {
			addCriterion("cityName >", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameGreaterThanOrEqualTo(String value) {
			addCriterion("cityName >=", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameLessThan(String value) {
			addCriterion("cityName <", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameLessThanOrEqualTo(String value) {
			addCriterion("cityName <=", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameLike(String value) {
			addCriterion("cityName like", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameNotLike(String value) {
			addCriterion("cityName not like", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameIn(List<String> values) {
			addCriterion("cityName in", values, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameNotIn(List<String> values) {
			addCriterion("cityName not in", values, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameBetween(String value1, String value2) {
			addCriterion("cityName between", value1, value2, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameNotBetween(String value1, String value2) {
			addCriterion("cityName not between", value1, value2, "cityName");
			return (Criteria) this;
		}

		public Criteria andAqiIsNull() {
			addCriterion("aqi is null");
			return (Criteria) this;
		}

		public Criteria andAqiIsNotNull() {
			addCriterion("aqi is not null");
			return (Criteria) this;
		}

		public Criteria andAqiEqualTo(String value) {
			addCriterion("aqi =", value, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiNotEqualTo(String value) {
			addCriterion("aqi <>", value, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiGreaterThan(String value) {
			addCriterion("aqi >", value, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiGreaterThanOrEqualTo(String value) {
			addCriterion("aqi >=", value, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiLessThan(String value) {
			addCriterion("aqi <", value, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiLessThanOrEqualTo(String value) {
			addCriterion("aqi <=", value, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiLike(String value) {
			addCriterion("aqi like", value, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiNotLike(String value) {
			addCriterion("aqi not like", value, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiIn(List<String> values) {
			addCriterion("aqi in", values, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiNotIn(List<String> values) {
			addCriterion("aqi not in", values, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiBetween(String value1, String value2) {
			addCriterion("aqi between", value1, value2, "aqi");
			return (Criteria) this;
		}

		public Criteria andAqiNotBetween(String value1, String value2) {
			addCriterion("aqi not between", value1, value2, "aqi");
			return (Criteria) this;
		}

		public Criteria andCoIsNull() {
			addCriterion("co is null");
			return (Criteria) this;
		}

		public Criteria andCoIsNotNull() {
			addCriterion("co is not null");
			return (Criteria) this;
		}

		public Criteria andCoEqualTo(String value) {
			addCriterion("co =", value, "co");
			return (Criteria) this;
		}

		public Criteria andCoNotEqualTo(String value) {
			addCriterion("co <>", value, "co");
			return (Criteria) this;
		}

		public Criteria andCoGreaterThan(String value) {
			addCriterion("co >", value, "co");
			return (Criteria) this;
		}

		public Criteria andCoGreaterThanOrEqualTo(String value) {
			addCriterion("co >=", value, "co");
			return (Criteria) this;
		}

		public Criteria andCoLessThan(String value) {
			addCriterion("co <", value, "co");
			return (Criteria) this;
		}

		public Criteria andCoLessThanOrEqualTo(String value) {
			addCriterion("co <=", value, "co");
			return (Criteria) this;
		}

		public Criteria andCoLike(String value) {
			addCriterion("co like", value, "co");
			return (Criteria) this;
		}

		public Criteria andCoNotLike(String value) {
			addCriterion("co not like", value, "co");
			return (Criteria) this;
		}

		public Criteria andCoIn(List<String> values) {
			addCriterion("co in", values, "co");
			return (Criteria) this;
		}

		public Criteria andCoNotIn(List<String> values) {
			addCriterion("co not in", values, "co");
			return (Criteria) this;
		}

		public Criteria andCoBetween(String value1, String value2) {
			addCriterion("co between", value1, value2, "co");
			return (Criteria) this;
		}

		public Criteria andCoNotBetween(String value1, String value2) {
			addCriterion("co not between", value1, value2, "co");
			return (Criteria) this;
		}

		public Criteria andO3IsNull() {
			addCriterion("o3 is null");
			return (Criteria) this;
		}

		public Criteria andO3IsNotNull() {
			addCriterion("o3 is not null");
			return (Criteria) this;
		}

		public Criteria andO3EqualTo(String value) {
			addCriterion("o3 =", value, "o3");
			return (Criteria) this;
		}

		public Criteria andO3NotEqualTo(String value) {
			addCriterion("o3 <>", value, "o3");
			return (Criteria) this;
		}

		public Criteria andO3GreaterThan(String value) {
			addCriterion("o3 >", value, "o3");
			return (Criteria) this;
		}

		public Criteria andO3GreaterThanOrEqualTo(String value) {
			addCriterion("o3 >=", value, "o3");
			return (Criteria) this;
		}

		public Criteria andO3LessThan(String value) {
			addCriterion("o3 <", value, "o3");
			return (Criteria) this;
		}

		public Criteria andO3LessThanOrEqualTo(String value) {
			addCriterion("o3 <=", value, "o3");
			return (Criteria) this;
		}

		public Criteria andO3Like(String value) {
			addCriterion("o3 like", value, "o3");
			return (Criteria) this;
		}

		public Criteria andO3NotLike(String value) {
			addCriterion("o3 not like", value, "o3");
			return (Criteria) this;
		}

		public Criteria andO3In(List<String> values) {
			addCriterion("o3 in", values, "o3");
			return (Criteria) this;
		}

		public Criteria andO3NotIn(List<String> values) {
			addCriterion("o3 not in", values, "o3");
			return (Criteria) this;
		}

		public Criteria andO3Between(String value1, String value2) {
			addCriterion("o3 between", value1, value2, "o3");
			return (Criteria) this;
		}

		public Criteria andO3NotBetween(String value1, String value2) {
			addCriterion("o3 not between", value1, value2, "o3");
			return (Criteria) this;
		}

		public Criteria andSo2IsNull() {
			addCriterion("so2 is null");
			return (Criteria) this;
		}

		public Criteria andSo2IsNotNull() {
			addCriterion("so2 is not null");
			return (Criteria) this;
		}

		public Criteria andSo2EqualTo(String value) {
			addCriterion("so2 =", value, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2NotEqualTo(String value) {
			addCriterion("so2 <>", value, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2GreaterThan(String value) {
			addCriterion("so2 >", value, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2GreaterThanOrEqualTo(String value) {
			addCriterion("so2 >=", value, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2LessThan(String value) {
			addCriterion("so2 <", value, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2LessThanOrEqualTo(String value) {
			addCriterion("so2 <=", value, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2Like(String value) {
			addCriterion("so2 like", value, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2NotLike(String value) {
			addCriterion("so2 not like", value, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2In(List<String> values) {
			addCriterion("so2 in", values, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2NotIn(List<String> values) {
			addCriterion("so2 not in", values, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2Between(String value1, String value2) {
			addCriterion("so2 between", value1, value2, "so2");
			return (Criteria) this;
		}

		public Criteria andSo2NotBetween(String value1, String value2) {
			addCriterion("so2 not between", value1, value2, "so2");
			return (Criteria) this;
		}

		public Criteria andNo2IsNull() {
			addCriterion("no2 is null");
			return (Criteria) this;
		}

		public Criteria andNo2IsNotNull() {
			addCriterion("no2 is not null");
			return (Criteria) this;
		}

		public Criteria andNo2EqualTo(String value) {
			addCriterion("no2 =", value, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2NotEqualTo(String value) {
			addCriterion("no2 <>", value, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2GreaterThan(String value) {
			addCriterion("no2 >", value, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2GreaterThanOrEqualTo(String value) {
			addCriterion("no2 >=", value, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2LessThan(String value) {
			addCriterion("no2 <", value, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2LessThanOrEqualTo(String value) {
			addCriterion("no2 <=", value, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2Like(String value) {
			addCriterion("no2 like", value, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2NotLike(String value) {
			addCriterion("no2 not like", value, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2In(List<String> values) {
			addCriterion("no2 in", values, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2NotIn(List<String> values) {
			addCriterion("no2 not in", values, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2Between(String value1, String value2) {
			addCriterion("no2 between", value1, value2, "no2");
			return (Criteria) this;
		}

		public Criteria andNo2NotBetween(String value1, String value2) {
			addCriterion("no2 not between", value1, value2, "no2");
			return (Criteria) this;
		}

		public Criteria andPm10IsNull() {
			addCriterion("pm10 is null");
			return (Criteria) this;
		}

		public Criteria andPm10IsNotNull() {
			addCriterion("pm10 is not null");
			return (Criteria) this;
		}

		public Criteria andPm10EqualTo(String value) {
			addCriterion("pm10 =", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10NotEqualTo(String value) {
			addCriterion("pm10 <>", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10GreaterThan(String value) {
			addCriterion("pm10 >", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10GreaterThanOrEqualTo(String value) {
			addCriterion("pm10 >=", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10LessThan(String value) {
			addCriterion("pm10 <", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10LessThanOrEqualTo(String value) {
			addCriterion("pm10 <=", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10Like(String value) {
			addCriterion("pm10 like", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10NotLike(String value) {
			addCriterion("pm10 not like", value, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10In(List<String> values) {
			addCriterion("pm10 in", values, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10NotIn(List<String> values) {
			addCriterion("pm10 not in", values, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10Between(String value1, String value2) {
			addCriterion("pm10 between", value1, value2, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm10NotBetween(String value1, String value2) {
			addCriterion("pm10 not between", value1, value2, "pm10");
			return (Criteria) this;
		}

		public Criteria andPm25IsNull() {
			addCriterion("pm25 is null");
			return (Criteria) this;
		}

		public Criteria andPm25IsNotNull() {
			addCriterion("pm25 is not null");
			return (Criteria) this;
		}

		public Criteria andPm25EqualTo(String value) {
			addCriterion("pm25 =", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25NotEqualTo(String value) {
			addCriterion("pm25 <>", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25GreaterThan(String value) {
			addCriterion("pm25 >", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25GreaterThanOrEqualTo(String value) {
			addCriterion("pm25 >=", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25LessThan(String value) {
			addCriterion("pm25 <", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25LessThanOrEqualTo(String value) {
			addCriterion("pm25 <=", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25Like(String value) {
			addCriterion("pm25 like", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25NotLike(String value) {
			addCriterion("pm25 not like", value, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25In(List<String> values) {
			addCriterion("pm25 in", values, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25NotIn(List<String> values) {
			addCriterion("pm25 not in", values, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25Between(String value1, String value2) {
			addCriterion("pm25 between", value1, value2, "pm25");
			return (Criteria) this;
		}

		public Criteria andPm25NotBetween(String value1, String value2) {
			addCriterion("pm25 not between", value1, value2, "pm25");
			return (Criteria) this;
		}

		public Criteria andWind_directionIsNull() {
			addCriterion("wind_direction is null");
			return (Criteria) this;
		}

		public Criteria andWind_directionIsNotNull() {
			addCriterion("wind_direction is not null");
			return (Criteria) this;
		}

		public Criteria andWind_directionEqualTo(String value) {
			addCriterion("wind_direction =", value, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionNotEqualTo(String value) {
			addCriterion("wind_direction <>", value, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionGreaterThan(String value) {
			addCriterion("wind_direction >", value, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionGreaterThanOrEqualTo(String value) {
			addCriterion("wind_direction >=", value, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionLessThan(String value) {
			addCriterion("wind_direction <", value, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionLessThanOrEqualTo(String value) {
			addCriterion("wind_direction <=", value, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionLike(String value) {
			addCriterion("wind_direction like", value, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionNotLike(String value) {
			addCriterion("wind_direction not like", value, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionIn(List<String> values) {
			addCriterion("wind_direction in", values, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionNotIn(List<String> values) {
			addCriterion("wind_direction not in", values, "wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionBetween(String value1, String value2) {
			addCriterion("wind_direction between", value1, value2,
					"wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_directionNotBetween(String value1, String value2) {
			addCriterion("wind_direction not between", value1, value2,
					"wind_direction");
			return (Criteria) this;
		}

		public Criteria andWind_forceIsNull() {
			addCriterion("wind_force is null");
			return (Criteria) this;
		}

		public Criteria andWind_forceIsNotNull() {
			addCriterion("wind_force is not null");
			return (Criteria) this;
		}

		public Criteria andWind_forceEqualTo(String value) {
			addCriterion("wind_force =", value, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceNotEqualTo(String value) {
			addCriterion("wind_force <>", value, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceGreaterThan(String value) {
			addCriterion("wind_force >", value, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceGreaterThanOrEqualTo(String value) {
			addCriterion("wind_force >=", value, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceLessThan(String value) {
			addCriterion("wind_force <", value, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceLessThanOrEqualTo(String value) {
			addCriterion("wind_force <=", value, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceLike(String value) {
			addCriterion("wind_force like", value, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceNotLike(String value) {
			addCriterion("wind_force not like", value, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceIn(List<String> values) {
			addCriterion("wind_force in", values, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceNotIn(List<String> values) {
			addCriterion("wind_force not in", values, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceBetween(String value1, String value2) {
			addCriterion("wind_force between", value1, value2, "wind_force");
			return (Criteria) this;
		}

		public Criteria andWind_forceNotBetween(String value1, String value2) {
			addCriterion("wind_force not between", value1, value2, "wind_force");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayIsNull() {
			addCriterion("temperature_day is null");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayIsNotNull() {
			addCriterion("temperature_day is not null");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayEqualTo(String value) {
			addCriterion("temperature_day =", value, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayNotEqualTo(String value) {
			addCriterion("temperature_day <>", value, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayGreaterThan(String value) {
			addCriterion("temperature_day >", value, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayGreaterThanOrEqualTo(String value) {
			addCriterion("temperature_day >=", value, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayLessThan(String value) {
			addCriterion("temperature_day <", value, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayLessThanOrEqualTo(String value) {
			addCriterion("temperature_day <=", value, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayLike(String value) {
			addCriterion("temperature_day like", value, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayNotLike(String value) {
			addCriterion("temperature_day not like", value, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayIn(List<String> values) {
			addCriterion("temperature_day in", values, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayNotIn(List<String> values) {
			addCriterion("temperature_day not in", values, "temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayBetween(String value1, String value2) {
			addCriterion("temperature_day between", value1, value2,
					"temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_dayNotBetween(String value1,
				String value2) {
			addCriterion("temperature_day not between", value1, value2,
					"temperature_day");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightIsNull() {
			addCriterion("temperature_night is null");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightIsNotNull() {
			addCriterion("temperature_night is not null");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightEqualTo(String value) {
			addCriterion("temperature_night =", value, "temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightNotEqualTo(String value) {
			addCriterion("temperature_night <>", value, "temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightGreaterThan(String value) {
			addCriterion("temperature_night >", value, "temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightGreaterThanOrEqualTo(String value) {
			addCriterion("temperature_night >=", value, "temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightLessThan(String value) {
			addCriterion("temperature_night <", value, "temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightLessThanOrEqualTo(String value) {
			addCriterion("temperature_night <=", value, "temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightLike(String value) {
			addCriterion("temperature_night like", value, "temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightNotLike(String value) {
			addCriterion("temperature_night not like", value,
					"temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightIn(List<String> values) {
			addCriterion("temperature_night in", values, "temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightNotIn(List<String> values) {
			addCriterion("temperature_night not in", values,
					"temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightBetween(String value1, String value2) {
			addCriterion("temperature_night between", value1, value2,
					"temperature_night");
			return (Criteria) this;
		}

		public Criteria andTemperature_nightNotBetween(String value1,
				String value2) {
			addCriterion("temperature_night not between", value1, value2,
					"temperature_night");
			return (Criteria) this;
		}

		public Criteria andWeather_typeIsNull() {
			addCriterion("weather_type is null");
			return (Criteria) this;
		}

		public Criteria andWeather_typeIsNotNull() {
			addCriterion("weather_type is not null");
			return (Criteria) this;
		}

		public Criteria andWeather_typeEqualTo(String value) {
			addCriterion("weather_type =", value, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeNotEqualTo(String value) {
			addCriterion("weather_type <>", value, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeGreaterThan(String value) {
			addCriterion("weather_type >", value, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeGreaterThanOrEqualTo(String value) {
			addCriterion("weather_type >=", value, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeLessThan(String value) {
			addCriterion("weather_type <", value, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeLessThanOrEqualTo(String value) {
			addCriterion("weather_type <=", value, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeLike(String value) {
			addCriterion("weather_type like", value, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeNotLike(String value) {
			addCriterion("weather_type not like", value, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeIn(List<String> values) {
			addCriterion("weather_type in", values, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeNotIn(List<String> values) {
			addCriterion("weather_type not in", values, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeBetween(String value1, String value2) {
			addCriterion("weather_type between", value1, value2, "weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_typeNotBetween(String value1, String value2) {
			addCriterion("weather_type not between", value1, value2,
					"weather_type");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameIsNull() {
			addCriterion("weather_type_name is null");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameIsNotNull() {
			addCriterion("weather_type_name is not null");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameEqualTo(String value) {
			addCriterion("weather_type_name =", value, "weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameNotEqualTo(String value) {
			addCriterion("weather_type_name <>", value, "weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameGreaterThan(String value) {
			addCriterion("weather_type_name >", value, "weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameGreaterThanOrEqualTo(String value) {
			addCriterion("weather_type_name >=", value, "weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameLessThan(String value) {
			addCriterion("weather_type_name <", value, "weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameLessThanOrEqualTo(String value) {
			addCriterion("weather_type_name <=", value, "weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameLike(String value) {
			addCriterion("weather_type_name like", value, "weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameNotLike(String value) {
			addCriterion("weather_type_name not like", value,
					"weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameIn(List<String> values) {
			addCriterion("weather_type_name in", values, "weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameNotIn(List<String> values) {
			addCriterion("weather_type_name not in", values,
					"weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameBetween(String value1, String value2) {
			addCriterion("weather_type_name between", value1, value2,
					"weather_type_name");
			return (Criteria) this;
		}

		public Criteria andWeather_type_nameNotBetween(String value1,
				String value2) {
			addCriterion("weather_type_name not between", value1, value2,
					"weather_type_name");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table weather
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_weather
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}