package com.pku.xinfeng.model;

public class Weather {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weather.cityId
	 * @mbggenerated
	 */
	private String cityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weather.cityName
	 * @mbggenerated
	 */
	private String cityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weather.aqi
	 * @mbggenerated
	 */
	private String aqi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weather.co
	 * @mbggenerated
	 */
	private String co;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weather.o3
	 * @mbggenerated
	 */
	private String o3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weather.so2
	 * @mbggenerated
	 */
	private String so2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weather.no2
	 * @mbggenerated
	 */
	private String no2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weather.pm10
	 * @mbggenerated
	 */
	private String pm10;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weather.pm25
	 * @mbggenerated
	 */
	private String pm25;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weather.wind_direction
	 * @mbggenerated
	 */
	private String wind_direction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weather.wind_force
	 * @mbggenerated
	 */
	private String wind_force;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weather.temperature_day
	 * @mbggenerated
	 */
	private String temperature_day;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weather.temperature_night
	 * @mbggenerated
	 */
	private String temperature_night;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weather.weather_type
	 * @mbggenerated
	 */
	private String weather_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column weather.weather_type_name
	 * @mbggenerated
	 */
	private String weather_type_name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weather.cityId
	 * @return  the value of weather.cityId
	 * @mbggenerated
	 */
	public String getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weather.cityId
	 * @param cityId  the value for weather.cityId
	 * @mbggenerated
	 */
	public void setCityId(String cityId) {
		this.cityId = cityId == null ? null : cityId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weather.cityName
	 * @return  the value of weather.cityName
	 * @mbggenerated
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weather.cityName
	 * @param cityName  the value for weather.cityName
	 * @mbggenerated
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName == null ? null : cityName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weather.aqi
	 * @return  the value of weather.aqi
	 * @mbggenerated
	 */
	public String getAqi() {
		return aqi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weather.aqi
	 * @param aqi  the value for weather.aqi
	 * @mbggenerated
	 */
	public void setAqi(String aqi) {
		this.aqi = aqi == null ? null : aqi.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weather.co
	 * @return  the value of weather.co
	 * @mbggenerated
	 */
	public String getCo() {
		return co;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weather.co
	 * @param co  the value for weather.co
	 * @mbggenerated
	 */
	public void setCo(String co) {
		this.co = co == null ? null : co.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weather.o3
	 * @return  the value of weather.o3
	 * @mbggenerated
	 */
	public String getO3() {
		return o3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weather.o3
	 * @param o3  the value for weather.o3
	 * @mbggenerated
	 */
	public void setO3(String o3) {
		this.o3 = o3 == null ? null : o3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weather.so2
	 * @return  the value of weather.so2
	 * @mbggenerated
	 */
	public String getSo2() {
		return so2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weather.so2
	 * @param so2  the value for weather.so2
	 * @mbggenerated
	 */
	public void setSo2(String so2) {
		this.so2 = so2 == null ? null : so2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weather.no2
	 * @return  the value of weather.no2
	 * @mbggenerated
	 */
	public String getNo2() {
		return no2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weather.no2
	 * @param no2  the value for weather.no2
	 * @mbggenerated
	 */
	public void setNo2(String no2) {
		this.no2 = no2 == null ? null : no2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weather.pm10
	 * @return  the value of weather.pm10
	 * @mbggenerated
	 */
	public String getPm10() {
		return pm10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weather.pm10
	 * @param pm10  the value for weather.pm10
	 * @mbggenerated
	 */
	public void setPm10(String pm10) {
		this.pm10 = pm10 == null ? null : pm10.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weather.pm25
	 * @return  the value of weather.pm25
	 * @mbggenerated
	 */
	public String getPm25() {
		return pm25;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weather.pm25
	 * @param pm25  the value for weather.pm25
	 * @mbggenerated
	 */
	public void setPm25(String pm25) {
		this.pm25 = pm25 == null ? null : pm25.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weather.wind_direction
	 * @return  the value of weather.wind_direction
	 * @mbggenerated
	 */
	public String getWind_direction() {
		return wind_direction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weather.wind_direction
	 * @param wind_direction  the value for weather.wind_direction
	 * @mbggenerated
	 */
	public void setWind_direction(String wind_direction) {
		this.wind_direction = wind_direction == null ? null : wind_direction
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weather.wind_force
	 * @return  the value of weather.wind_force
	 * @mbggenerated
	 */
	public String getWind_force() {
		return wind_force;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weather.wind_force
	 * @param wind_force  the value for weather.wind_force
	 * @mbggenerated
	 */
	public void setWind_force(String wind_force) {
		this.wind_force = wind_force == null ? null : wind_force.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weather.temperature_day
	 * @return  the value of weather.temperature_day
	 * @mbggenerated
	 */
	public String getTemperature_day() {
		return temperature_day;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weather.temperature_day
	 * @param temperature_day  the value for weather.temperature_day
	 * @mbggenerated
	 */
	public void setTemperature_day(String temperature_day) {
		this.temperature_day = temperature_day == null ? null : temperature_day
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weather.temperature_night
	 * @return  the value of weather.temperature_night
	 * @mbggenerated
	 */
	public String getTemperature_night() {
		return temperature_night;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weather.temperature_night
	 * @param temperature_night  the value for weather.temperature_night
	 * @mbggenerated
	 */
	public void setTemperature_night(String temperature_night) {
		this.temperature_night = temperature_night == null ? null
				: temperature_night.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weather.weather_type
	 * @return  the value of weather.weather_type
	 * @mbggenerated
	 */
	public String getWeather_type() {
		return weather_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weather.weather_type
	 * @param weather_type  the value for weather.weather_type
	 * @mbggenerated
	 */
	public void setWeather_type(String weather_type) {
		this.weather_type = weather_type == null ? null : weather_type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column weather.weather_type_name
	 * @return  the value of weather.weather_type_name
	 * @mbggenerated
	 */
	public String getWeather_type_name() {
		return weather_type_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column weather.weather_type_name
	 * @param weather_type_name  the value for weather.weather_type_name
	 * @mbggenerated
	 */
	public void setWeather_type_name(String weather_type_name) {
		this.weather_type_name = weather_type_name == null ? null
				: weather_type_name.trim();
	}

	//add
	private Integer id;
	private String cityNameEn;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCityNameEn() {
		return cityNameEn;
	}

	public void setCityNameEn(String cityNameEn) {
		this.cityNameEn = cityNameEn;
	}
}